AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
