language: ruby
matrix:
  include:
    - rvm: 2.1.9
      env: PUPPET_VERSION='~> 4.5'
    - rvm: 2.4.2
      env: PUPPET_VERSION='~> 5.0'
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
env:
  - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"

branches:
  only:
    - master
    - develop
    - /^\d+\.\d+(\.\d+)$*/

before_install:
  - gem update bundler

script:
  - bundle exec rake test
